#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 08-03-08 07:53 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace MediaMobile.MediaLibrary
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, TypeName="PlaylistElement")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false, ElementName="PlaylistElement")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class PlaylistElement
    {
        
        /// <remarks/>
        private string playlistName;
        
        /// <remarks/>
        private System.Collections.Generic.List<MediaObjectElement> mediaObjectElement;
        
        /// <remarks/>
        private System.Collections.Generic.List<EmbeddedPlaylistElement> embeddedPlaylistElement;
        
        public PlaylistElement()
        {
        }
        
        public PlaylistElement(string playlistName, System.Collections.Generic.List<MediaObjectElement> mediaObjectElement, System.Collections.Generic.List<EmbeddedPlaylistElement> embeddedPlaylistElement)
        {
            this.playlistName = playlistName;
            this.mediaObjectElement = mediaObjectElement;
            this.embeddedPlaylistElement = embeddedPlaylistElement;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="PlaylistName")]
        public string PlaylistName
        {
            get
            {
                return this.playlistName;
            }
            set
            {
                if ((this.playlistName != value))
                {
                    this.playlistName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MediaObjectElement")]
        public System.Collections.Generic.List<MediaObjectElement> MediaObjectElement
        {
            get
            {
                return this.mediaObjectElement;
            }
            set
            {
                if ((this.mediaObjectElement != value))
                {
                    this.mediaObjectElement = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("EmbeddedPlaylistElement")]
        public System.Collections.Generic.List<EmbeddedPlaylistElement> EmbeddedPlaylistElement
        {
            get
            {
                return this.embeddedPlaylistElement;
            }
            set
            {
                if ((this.embeddedPlaylistElement != value))
                {
                    this.embeddedPlaylistElement = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, TypeName="MediaObjectElement")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false, ElementName="MediaObjectElement")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class MediaObjectElement
    {
        
        /// <remarks/>
        private string filename;
        
        public MediaObjectElement()
        {
        }
        
        public MediaObjectElement(string filename)
        {
            this.filename = filename;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="Filename")]
        public string Filename
        {
            get
            {
                return this.filename;
            }
            set
            {
                if ((this.filename != value))
                {
                    this.filename = value;
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, TypeName="EmbeddedPlaylistElement")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false, ElementName="EmbeddedPlaylistElement")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class EmbeddedPlaylistElement
    {
        
        /// <remarks/>
        private string playlistFilename;
        
        public EmbeddedPlaylistElement()
        {
        }
        
        public EmbeddedPlaylistElement(string playlistFilename)
        {
            this.playlistFilename = playlistFilename;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="PlaylistFilename")]
        public string PlaylistFilename
        {
            get
            {
                return this.playlistFilename;
            }
            set
            {
                if ((this.playlistFilename != value))
                {
                    this.playlistFilename = value;
                }
            }
        }
    }
}
